package com.wealth.platform;
import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.web.bind.annotation.*; import java.math.BigDecimal; import java.time.LocalDate; import java.util.*;
@RestController @RequestMapping("/api") @CrossOrigin(origins="${app.frontend-url:http://localhost:5173}") public class ApiController {
 private final UserRepository users; private final PortfolioRepository portfolio; private final TransactionRepository transactions; private final JwtService jwt; private final BCryptPasswordEncoder encoder=new BCryptPasswordEncoder();
 ApiController(UserRepository u,PortfolioRepository p,TransactionRepository t,JwtService j){users=u;portfolio=p;transactions=t;jwt=j;}
 record Credentials(@Email String email,@Size(min=8) String password){} record Token(String token){}
 @PostMapping("/auth/register") ResponseEntity<?> register(@RequestBody Credentials c){if(users.findByEmail(c.email()).isPresent())return ResponseEntity.status(409).body(Map.of("error","Email already registered")); User u=users.save(new User(c.email(),encoder.encode(c.password())));return ResponseEntity.status(201).body(new Token(jwt.create(u)));}
 @PostMapping("/auth/login") ResponseEntity<?> login(@RequestBody Credentials c){return users.findByEmail(c.email()).filter(u->encoder.matches(c.password(),u.passwordHash)).<ResponseEntity<?>>map(u->ResponseEntity.ok(new Token(jwt.create(u)))).orElseGet(()->ResponseEntity.status(401).body(Map.of("error","Invalid credentials")));}
 private Long uid(Authentication a){return (Long)a.getPrincipal();} private User user(Authentication a){return users.getReferenceById(uid(a));}
 @GetMapping("/dashboard") Map<String,Object> dashboard(Authentication a){var items=portfolio.findByOwnerId(uid(a)); var tx=transactions.findByOwnerIdOrderByDateDesc(uid(a)); BigDecimal assets=items.stream().map(i->i.value==null?BigDecimal.ZERO:i.value).reduce(BigDecimal.ZERO,BigDecimal::add); BigDecimal liabilities=items.stream().map(i->i.liability==null?BigDecimal.ZERO:i.liability).reduce(BigDecimal.ZERO,BigDecimal::add); BigDecimal income=tx.stream().filter(t->t.direction==Transaction.Direction.INCOME).map(t->t.amount).reduce(BigDecimal.ZERO,BigDecimal::add); BigDecimal expenses=tx.stream().filter(t->t.direction==Transaction.Direction.EXPENSE).map(t->t.amount).reduce(BigDecimal.ZERO,BigDecimal::add); return Map.of("netWorth",assets.subtract(liabilities),"assets",assets,"liabilities",liabilities,"income",income,"expenses",expenses,"cashFlow",income.subtract(expenses),"items",items,"transactions",tx);}
 @PostMapping("/portfolio") PortfolioItem addItem(@RequestBody PortfolioItem i,Authentication a){i.id=null;i.owner=user(a);if(i.liability==null)i.liability=BigDecimal.ZERO;return portfolio.save(i);}
 @PostMapping("/transactions") Transaction addTransaction(@RequestBody Transaction t,Authentication a){t.id=null;t.owner=user(a);return transactions.save(t);}
 @GetMapping("/transactions") List<Transaction> listTransactions(@RequestParam(required=false) String category,Authentication a){return transactions.findByOwnerIdOrderByDateDesc(uid(a)).stream().filter(t->category==null||category.equalsIgnoreCase(t.category)).toList();}
 @PostMapping("/demo/seed") Map<String,Object> seedDemo(Authentication a){if(!portfolio.findByOwnerId(uid(a)).isEmpty())return dashboard(a); User owner=user(a); List<PortfolioItem> items=new ArrayList<>(); items.add(item(owner,PortfolioItem.AssetType.BANK_ACCOUNT,"HDFC Bank · Salary", "185400","0")); items.add(item(owner,PortfolioItem.AssetType.BANK_ACCOUNT,"ICICI Bank · Savings", "96400","0")); items.add(item(owner,PortfolioItem.AssetType.STOCK,"Nifty 50 Index", "312000","0")); items.add(item(owner,PortfolioItem.AssetType.STOCK,"Tata Consultancy Services", "186500","0")); items.add(item(owner,PortfolioItem.AssetType.MUTUAL_FUND,"Parag Parikh Flexi Cap", "428000","0")); items.add(item(owner,PortfolioItem.AssetType.MUTUAL_FUND,"Mirae Asset Large & Midcap", "245000","0")); items.add(item(owner,PortfolioItem.AssetType.FIXED_DEPOSIT,"SBI Fixed Deposit", "150000","0")); items.add(item(owner,PortfolioItem.AssetType.CREDIT_CARD,"HDFC Regalia", "0","18400")); items.add(item(owner,PortfolioItem.AssetType.LOAN,"Home loan", "0","2840000")); portfolio.saveAll(items); LocalDate today=LocalDate.now(); transactions.saveAll(List.of(tx(owner,today.minusDays(1),Transaction.Direction.EXPENSE,"Food & dining","Dinner at The Table", "1860"),tx(owner,today.minusDays(2),Transaction.Direction.EXPENSE,"Transport","Uber rides", "780"),tx(owner,today.minusDays(3),Transaction.Direction.INCOME,"Salary","Monthly salary", "185000"),tx(owner,today.minusDays(5),Transaction.Direction.EXPENSE,"Shopping","Nike running shoes", "6495"),tx(owner,today.minusDays(7),Transaction.Direction.EXPENSE,"Bills","Electricity bill", "3260"),tx(owner,today.minusDays(9),Transaction.Direction.EXPENSE,"Investments","Monthly SIP", "25000"))); return dashboard(a);}
 private PortfolioItem item(User owner,PortfolioItem.AssetType type,String name,String value,String liability){PortfolioItem i=new PortfolioItem();i.owner=owner;i.type=type;i.name=name;i.value=new BigDecimal(value);i.liability=new BigDecimal(liability);return i;}
 private Transaction tx(User owner,LocalDate date,Transaction.Direction direction,String category,String description,String amount){Transaction t=new Transaction();t.owner=owner;t.date=date;t.direction=direction;t.category=category;t.description=description;t.amount=new BigDecimal(amount);return t;}
}
