import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer,PieChart,Pie,Cell} from 'recharts';
import {LayoutDashboard,CreditCard,RefreshCcw,Landmark,Webhook,FileCheck,Search,Bell,Plus,ArrowUpRight,CheckCircle2,XCircle,Clock3,WalletCards} from 'lucide-react';
import './styles.css';
import './notifications.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:8080/api/v1';
const apiFetch=(url,options={})=>fetch(url,{...options,headers:{...(options.headers||{}),...(localStorage.getItem('payflow_token')?{Authorization:`Bearer ${localStorage.getItem('payflow_token')}`}:{})}});
const money=(value=0)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value);
const colors=['#6d5dfc','#27c7a8','#ffb648','#ef6f83'];

function App(){
 const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('payflow_user')||'null'));
 const [view,setView]=useState('Overview'),[analytics,setAnalytics]=useState(null),[payments,setPayments]=useState([]),[loading,setLoading]=useState(true),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[notifications,setNotifications]=useState(false);
 const load=async()=>{setLoading(true);try{const [a,p]=await Promise.all([apiFetch(`${API}/analytics/dashboard`).then(r=>r.json()),apiFetch(`${API}/payments?size=50`).then(r=>r.json())]);setAnalytics(a);setPayments(p.content||[]);}finally{setLoading(false)}};
 useEffect(()=>{if(user)load()},[user]); const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2800)};
 const action=async(id,type,body)=>{const r=await apiFetch(`${API}/payments/${id}/${type}`,{method:'POST',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)return notify(data.error||'Request failed');notify(`Payment ${type} completed`);load()};
 const create=async form=>{const r=await apiFetch(`${API}/payments`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({...form,merchantId:user.merchantId})});const p=await r.json();if(!r.ok)return notify(p.error||'Could not create payment');await action(p.id,'authorize',{forceSuccess:true});setModal(false)};
 const nav=[['Overview',LayoutDashboard],['Payments',CreditCard],['Refunds',RefreshCcw],['Settlements',Landmark],['Webhooks',Webhook],['Reconciliation',FileCheck]];
 if(!user)return <Login onLogin={setUser}/>;
 const alerts=payments.filter(p=>['FAILED','CAPTURED','REFUNDED','PARTIALLY_REFUNDED'].includes(p.status)).slice(0,6);
 return <div className="shell"><aside><div className="brand"><span>PF</span>PayFlow</div><div className="workspace"><small>MERCHANT WORKSPACE</small><strong>{user.businessName}</strong><span>{user.merchantId}</span></div><nav>{nav.map(([n,I])=><button className={view===n?'active':''} onClick={()=>setView(n)} key={n}><I size={19}/>{n}</button>)}</nav><div className="mode"><span></span><div><small>SYSTEM STATUS</small><b>All systems operational</b></div></div></aside><main><header><div><h1>{view}</h1><p>{view==='Overview'?'Your payment operations at a glance':'Manage '+view.toLowerCase()}</p></div><div className="header-actions"><button className="icon"><Search size={19}/></button><div className="notification-wrap"><button className="icon" aria-label="Notifications" onClick={()=>setNotifications(!notifications)}><Bell size={19}/>{alerts.some(p=>p.status==='FAILED')&&<i/>}</button>{notifications&&<NotificationPanel items={alerts} close={()=>setNotifications(false)}/>}</div><button className="avatar" title="Sign out" onClick={()=>{localStorage.removeItem('payflow_token');localStorage.removeItem('payflow_user');setUser(null)}}>{user.email.slice(0,2).toUpperCase()}</button><button className="primary" onClick={()=>setModal(true)}><Plus size={18}/>Create payment</button></div></header>
 {loading?<div className="loading">Loading payment data…</div>:view==='Overview'?<Overview data={analytics} payments={payments}/>:<Operations view={view} payments={payments} action={action} reload={load} notify={notify}/>}</main>{modal&&<CreateModal close={()=>setModal(false)} submit={create}/>} {toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}</div>
}

function Login({onLogin}){const [email,setEmail]=useState('demo@payflow.local'),[password,setPassword]=useState('Demo@12345'),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Login failed');localStorage.setItem('payflow_token',data.token);localStorage.setItem('payflow_user',JSON.stringify(data));onLogin(data)}catch(e){setError(e.message)}finally{setBusy(false)}};return <div className="login-page"><div className="login-card"><div className="login-brand"><span>PF</span>PayFlow</div><h1>Welcome back</h1><p>Sign in to your merchant dashboard</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="login-error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in securely'}</button></form><small>Demo: demo@payflow.local / Demo@12345</small></div></div>}

function Overview({data,payments}){const pie=Object.entries(data.methodBreakdown||{}).map(([name,value])=>({name,value}));return <><section className="metrics">
 <Metric icon={WalletCards} label="Total payment volume" value={money(data.totalVolume)} detail="Processed across all methods" trend="+12.8%"/>
 <Metric icon={CheckCircle2} label="Successful payments" value={data.successfulPayments} detail={`${data.successRate}% success rate`} trend="+4.2%" green/>
 <Metric icon={Clock3} label="Pending settlement" value={money(data.pendingSettlement)} detail="Next settlement tomorrow"/>
 <Metric icon={RefreshCcw} label="Total refunds" value={money(data.refundAmount)} detail="Across captured payments"/>
 </section><section className="grid"><div className="panel chart"><Title title="Payment volume" subtitle="Last seven days"/><ResponsiveContainer width="100%" height={260}><AreaChart data={data.trend}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#6d5dfc" stopOpacity=".28"/><stop offset="1" stopColor="#6d5dfc" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="label" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={v=>`₹${v/1000}k`}/><Tooltip formatter={v=>money(v)}/><Area type="monotone" dataKey="amount" stroke="#6d5dfc" strokeWidth={3} fill="url(#g)"/></AreaChart></ResponsiveContainer></div>
 <div className="panel methods"><Title title="Payment methods" subtitle="Transaction mix"/><div className="pie"><ResponsiveContainer width="55%" height={210}><PieChart><Pie data={pie} dataKey="value" innerRadius={62} outerRadius={88} paddingAngle={3}>{pie.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie></PieChart></ResponsiveContainer><div className="legend">{pie.map((x,i)=><div key={x.name}><span style={{background:colors[i%colors.length]}}></span><b>{x.name}</b><em>{x.value}</em></div>)}</div></div></div></section><PaymentTable payments={payments.slice(0,8)}/></>}
function Metric({icon:I,label,value,detail,trend,green}) {return <div className="metric"><div className="metric-top"><span className={green?'mint':''}><I size={20}/></span>{trend&&<em><ArrowUpRight size={13}/>{trend}</em>}</div><p>{label}</p><h2>{value}</h2><small>{detail}</small></div>}
function Title({title,subtitle}){return <div className="title"><div><h3>{title}</h3><p>{subtitle}</p></div><button>Last 7 days⌄</button></div>}
function PaymentTable({payments,action}){return <div className="panel table-panel"><Title title="Recent payments" subtitle="Latest activity across your account"/><div className="table-wrap"><table><thead><tr><th>PAYMENT</th><th>CUSTOMER</th><th>METHOD</th><th>AMOUNT</th><th>STATUS</th><th>CREATED</th>{action&&<th>ACTION</th>}</tr></thead><tbody>{payments.map(p=><tr key={p.id}><td><strong>{p.id}</strong><small>{p.description}</small></td><td>{p.customerEmail||'—'}</td><td><span className="method"><CreditCard size={15}/>{p.method}</span></td><td><b>{money(p.amount)}</b></td><td><Status value={p.status}/></td><td>{new Date(p.createdAt).toLocaleDateString('en-IN',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</td>{action&&<td>{p.status==='FAILED'?<button className="tiny" onClick={()=>action(p.id,'retry')}>Retry</button>:p.status==='AUTHORIZED'?<button className="tiny" onClick={()=>action(p.id,'capture')}>Capture</button>:'—'}</td>}</tr>)}</tbody></table></div></div>}
function Status({value}){let ok=['CAPTURED','AUTHORIZED'].includes(value),bad=value==='FAILED';return <span className={`status ${ok?'ok':bad?'bad':'wait'}`}>{ok?<CheckCircle2/>:bad?<XCircle/>:<Clock3/>}{value.replace('_',' ')}</span>}
function NotificationPanel({items,close}){return <div className="notifications"><div className="notifications-head"><b>Notifications</b><button onClick={close}>×</button></div>{items.length===0?<p className="no-alerts">No recent activity</p>:items.map(p=><button className="alert" key={p.id} onClick={close}><Status value={p.status}/><span><b>{p.status==='FAILED'?'Payment failed':p.status.includes('REFUND')?'Refund updated':'Payment captured'}</b><small>{p.id} · {money(p.amount)}</small></span></button>)}</div>}
function Operations({view,payments,action,reload,notify}){if(view==='Payments')return <PaymentTable payments={payments} action={action}/>;if(view==='Refunds')return <Refunds/>;if(view==='Settlements')return <Settlements notify={notify}/>;return <div className="empty panel"><div className="empty-icon">{view==='Webhooks'?<Webhook/>:<FileCheck/>}</div><h2>{view}</h2><p>This module is connected to the backend API and ready to operate. Use the documented API endpoints for detailed workflows.</p>{view==='Reconciliation'&&<button className="primary" onClick={async()=>{let x=await apiFetch(`${API}/reconciliation/run`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(r=>r.json());notify(`Reconciled ${x.recordsScanned} records — ${x.status}`)}}>Run reconciliation</button>}</div>}
function Refunds(){const [rows,setRows]=useState([]);useEffect(()=>{apiFetch(`${API}/refunds`).then(r=>r.json()).then(setRows)},[]);return <div className="panel table-panel"><Title title="Refund history" subtitle="Money returned to customers"/><div className="table-wrap"><table><thead><tr><th>REFUND</th><th>PAYMENT</th><th>AMOUNT</th><th>REASON</th><th>CREATED</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.id}</strong></td><td>{r.paymentId}</td><td><b>{money(r.amount)}</b></td><td>{r.reason}</td><td>{new Date(r.createdAt).toLocaleString('en-IN')}</td></tr>)}</tbody></table>{rows.length===0&&<p className="no-rows">No refunds have been created yet.</p>}</div></div>}
function Settlements({notify}){const [rows,setRows]=useState([]);const load=()=>apiFetch(`${API}/settlements?merchantId=merchant_demo`).then(r=>r.json()).then(setRows);useEffect(load,[]);const generate=async()=>{await apiFetch(`${API}/settlements`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({merchantId:'merchant_demo'})});notify('Settlement generated');load()};return <div className="panel table-panel"><div className="title settlement-title"><div><h3>Settlement history</h3><p>Captured funds paid out after processing fees</p></div><button className="primary" onClick={generate}><Plus size={15}/>Generate settlement</button></div><div className="table-wrap"><table><thead><tr><th>SETTLEMENT</th><th>GROSS</th><th>PROCESSING FEE</th><th>NET PAYOUT</th><th>STATUS</th><th>CREATED</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.id}</strong></td><td>{money(r.grossAmount)}</td><td>{money(r.feeAmount)}</td><td><b>{money(r.netAmount)}</b></td><td><Status value={r.status}/></td><td>{new Date(r.createdAt).toLocaleString('en-IN')}</td></tr>)}</tbody></table>{rows.length===0&&<p className="no-rows">No settlements generated yet.</p>}</div></div>}
function CreateModal({close,submit}){const [f,setF]=useState({merchantId:'merchant_demo',amount:'',currency:'INR',method:'card',description:'',customerEmail:''});return <div className="backdrop"><form className="modal" onSubmit={e=>{e.preventDefault();submit({...f,amount:Number(f.amount)})}}><div><h2>Create a payment</h2><button type="button" onClick={close}>×</button></div><p>Start a new payment intent with a unique idempotency key.</p><label>Amount<input required min="1" type="number" placeholder="2500" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></label><div className="row"><label>Currency<select value={f.currency} onChange={e=>setF({...f,currency:e.target.value})}><option>INR</option><option>USD</option></select></label><label>Payment method<select value={f.method} onChange={e=>setF({...f,method:e.target.value})}><option value="card">Card</option><option value="upi">UPI</option><option value="netbanking">Net banking</option><option value="wallet">Wallet</option></select></label></div><label>Customer email<input type="email" placeholder="customer@example.com" value={f.customerEmail} onChange={e=>setF({...f,customerEmail:e.target.value})}/></label><label>Description<input placeholder="Order #1042" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><footer><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Create & authorize</button></footer></form></div>}
createRoot(document.getElementById('root')).render(<App/>);
